Modified

diff --git a/.github/workflows/Newman_backend_test.yaml b/.github/workflows/Newman_backend_test.yaml
--- a/.github/workflows/Newman_backend_test.yaml
+++ b/.github/workflows/Newman_backend_test.yaml
@@ -321,16 +321,6 @@ jobs:
       - name: List Running containers
         run: docker ps -a
  
-      - name: Fail CI if Newman failed
-        if: always()
-        run: |
-          if [ ${{ steps.newman.outcome }} != 'success' ]; then
-            echo "Newman tests failed. Blocking merge."
-            exit 1
-          else
-            echo "Newman passed."
-          fi
- 
       - name: Tear Down Docker Containers
         if: always()
         run: docker compose -f ./docker-compose.yaml down
@@ -352,7 +342,7 @@ jobs:
     name: Aggregate Newman Results
     runs-on: ubuntu-latest
     if: needs.build_and_test.outputs.outcome == 'newman_failed'
-    needs: build_and_test
+    needs: [build_and_test]
     outputs:
       newman_failed_any: ${{ steps.setflag.outputs.newman_failed_any }}
     steps:
@@ -379,7 +369,7 @@ jobs:
   map_pr_to_discord:
     name: Notify Developer or Admin
     runs-on: ubuntu-latest
-    needs: aggregate_results
+    needs: [aggregate_results]
     if: needs.build_and_test.outputs.outcome == 'newman_failed'
     outputs:
       discord_mention: ${{ steps.map.outputs.discord_mention }}
@@ -510,3 +500,13 @@ jobs:
                -X POST \
                -d "{\"content\": \"${MESSAGE}\"}" \
                "$DISCORD_WEBHOOK_URL"
+
+  final_check:
+    name: Fail workflow if needed
+    runs-on: ubuntu-latest
+    needs: [build_and_test]
+    if: needs.build_and_test.outputs.outcome != 'success'
+    steps:
+      - run: |
+          echo " Failing workflow to block merge (reason: ${{ needs.build_and_test.outputs.outcome }})"
+          exit 1
